cmake_minimum_required(VERSION 3.23.0) # Гарантия совместимости

project(PGR_File) # Далее следует описание программного проекта с заданным именем
# Эта команда выполняет проверки, чтобы убедиться в пригодности среды для сборки программного обеспечения
# Например, проверяет наличие компиляторов и других инструментов сборки, в также определяет такие свойства, как порядок байтов на хост-машине и целевой машине.

add_executable(PGR_File) # Эта команда создаёт цель
# Цель - это имя, которое разработчик присваивает набору свойств
# Примеры свойств, за которыми целевому объекту может потребоваться следить:
# - Тип артефакта (исполняемый файл, библиотека, набор заголовочных файлов и т. д.)
# - Исходные файлы
# - Включить каталоги
# - Вывод имени исполняемого файла или библиотеки.
# - Зависимости
# - Флаги компилятора и компоновщика

# Когда имя для цели, можно начать связывать с ней свойства, такие как исходные файлы, которые мы хотим скомпилировать и связать
target_sources( # Эта функция принимает в качестве аргументов имя целевого объекта, за которым следует один или несколько наборов файлов
    PGR_File
    PRIVATE
    main.c
)