cmake_minimum_required(VERSION 3.23.0) # Гарантия совместимости

project(PGR_File) # Далее следует описание программного проекта с заданным именем
# Эта команда выполняет проверки, чтобы убедиться в пригодности среды для сборки программного обеспечения
# Например, проверяет наличие компиляторов и других инструментов сборки, в также определяет такие свойства, как порядок байтов на хост-машине и целевой машине.

add_executable(PGR_File) # Эта команда создаёт цель
# Цель - это имя, которое разработчик присваивает набору свойств
# Примеры свойств, за которыми целевому объекту может потребоваться следить:
# - Тип артефакта (исполняемый файл, библиотека, набор заголовочных файлов и т. д.)
# - Исходные файлы
# - Включить каталоги
# - Вывод имени исполняемого файла или библиотеки.
# - Зависимости
# - Флаги компилятора и компоновщика

# Когда имя для цели, можно начать связывать с ней свойства, такие как исходные файлы, которые мы хотим скомпилировать и связать
target_sources( # Эта функция принимает в качестве аргументов имя целевого объекта, за которым следует один или несколько наборов файлов
    PGR_File
    PRIVATE
    main.c
)

add_library(PGR_File_core_lib) # Это работает точно так же, как add_executable(), но для библиотек
# Заголовочные файлы не создаются напрямую как единицы трансляции, то есть они не являются обязательным требованием для сборки
# Нам нужно знать о заголовочных файлах, чтобы собрать другие части заданной целевой системы
target_sources( PGR_File_core_lib
    PRIVATE
        core/core_src.c # Есть файл реализации в качестве PRIVATE исходного кода, как и в случае с исполняемым файлом ранее

    PUBLIC # PUBLIC в качестве заголовочного файла. Это позволяет пользователям библиотеки «видеть» заголовочные файлы библиотеки
        FILE_SET pgr_file_core_headers # Объект FILE_SET, представляет набор файлов, описываемых как единое целое
        # FILE_SET <name> это имя коллекции FILE_SET. Это идентификатор, который используют для описания коллекции в других контекстах.
        TYPE HEADERS # TYPE <type> речь идёт именно о таких файлах. Чаще всего это заголовочные файлы, но более новые версии CMake поддерживают и другие типы, например, модули C++20
        BASE_DIRS # Это «базовые» местоположения файлов. Проще всего это понять как местоположения, которые будут описаны компиляторам для обнаружения заголовочных файлов с помощью -Iфлагов
            core
        FILES # Это список файлов, аналогичный списку исходных файлов реализации, представленному ранее
            core/core_inc.h
)

target_link_libraries(PGR_File # Команда делает гораздо больше, чем просто вызывает компоновщики. Она описывает взаимосвязи между целевыми объектами в общем виде
    PRIVATE
        PGR_File_core_lib
)